GET http://localhost:8888/api/v1/images

###

GET http://localhost:8888/api/v1/image/5ecd672cf1748c421305c4eb

###

POST http://localhost:8888/api/v1/image/new
Content-Type: application/json

{
  "name": "Lake Mary Morning2",
  "description": "Lake Mary at sunrise.  ",
  "creator": "5ecd7a388b82654e79a8b2bb"
}

###

DELETE http://localhost:8888/api/v1/image/delete/5ecd672cf1748c421305c4eb

###

PATCH http://localhost:8888/api/v1/image/update/5ecd314a6f4516207ed5b860
Content-Type: application/json

{
  "description": "Lake Mary at sunrise. So pretty huh!"
}

###

GET http://localhost:8888/api/v1/user/5ecd7a388b82654e79a8b2bb

###

GET http://localhost:8888/api/v1/user/5ecd4038211bea27f8e42fac/images

###

POST http://localhost:8888/api/v1/user/new
Content-Type: application/json

{
  "email": "clint.losee@gmail.com",
  "password": "flyfish80"
}
